### ISSUE TITLE
Music stops working if queue cleared while playing

### ISSUE THREAD

**Issue by instantrahmen** [instantrahmen/HelperBot#2]
If the music player queue is cleared while playing music, it will refuse to play again until the bot is restarted.

### Steps to reproduce:
1. Play a song or playlist
2. Without pausing, clear the playlist with /clear-queue
3. Attempt to add another song or playlist to queue

**Comment by instantrahmen** [comment]
Log output: 
```
Audio player transitioned from playing to idle
{
  error: TypeError: Cannot read properties of undefined (reading 'url')
      at MusicPlayer.<anonymous> (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:118:45)
      at step HelperBot/packages/server/src/bot/components/MusicPlayer.ts:67:23)
      at Object.next (/packages/server/src/bot/components/MusicPlayer.ts:48:53)
      at HelperBot/packages/server/src/bot/components/MusicPlayer.ts:42:71
      at new Promise (<anonymous>)
      at __awaiter (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:38:12)
      at MusicPlayer.play (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:217:16)
      at MusicPlayer.<anonymous> (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:159:16)
      at step (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:67:23)
      at Object.next (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:48:53)
}
The audio player is idle!
Error: Unable to play song: Cannot read properties of undefined (reading 'url')
    at MusicPlayer.<anonymous> (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:126:13)
    at step (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:67:23)
    at Object.next (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:48:53)
    at HelperBot/packages/server/src/bot/components/MusicPlayer.ts:42:71
    at new Promise (<anonymous>)
    at __awaiter (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:38:12)
    at MusicPlayer.play (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:217:16)
    at MusicPlayer.<anonymous> (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:159:16)
    at step (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:67:23)
    at Object.next (HelperBot/packages/server/src/bot/components/MusicPlayer.ts:48:53)
```
