### ISSUE TITLE
Unknown interaction on connection to voice channel

### ISSUE THREAD

**Issue by instantrahmen** [instantrahmen/HelperBot#3]
Whenever a connection to any VC is initiated, the following error is logged:
```
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:103:5) {
  method: 'post',
  path: '/interactions/SECRET/SECRET/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async CommandInteraction.reply (HelperBot/node_modules/.pnpm/discord.js@13.7.0/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:103:5) {
  method: 'post',
  path: '/interactions/SECRET/SECRET/callback',
  code: 10062,
  httpStatus: 404,
  requestData: { json: { type: 4, data: [Object] }, files: [] }
}
```

**Comment by instantrahmen** [comment]
Fixed in [most recent commit](https://github.com/instantrahmen/HelperBot/commit/ebbbd3194adebd7e8b96034dda51dac865fe8245)
